apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-extraction-service-config
  labels:
    app: extraction-service
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
