apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  OIDC_CLIENT_ID: {{ .Values.secrets.OIDC_CLIENT_ID | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.OIDC_CLIENT_SECRET | b64enc | quote }}
  OIDC_ISSUER_URL: {{ .Values.secrets.OIDC_ISSUER_URL | b64enc | quote }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc | quote }}
  JWT_PRIVATE_KEY: {{ .Values.secrets.JWT_PRIVATE_KEY | b64enc | quote }}
