apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  OIDC_CLIENT_ID: {{ required "A valid .Values.secrets.OIDC_CLIENT_ID is required!" .Values.secrets.OIDC_CLIENT_ID | quote }}
  OIDC_CLIENT_SECRET: {{ required "A valid .Values.secrets.OIDC_CLIENT_SECRET is required!" .Values.secrets.OIDC_CLIENT_SECRET | quote }}
  OIDC_ISSUER_URL: {{ required "A valid .Values.secrets.OIDC_ISSUER_URL is required!" .Values.secrets.OIDC_ISSUER_URL | quote }}
  DATABASE_URL: {{ required "A valid .Values.secrets.DATABASE_URL is required!" .Values.secrets.DATABASE_URL | quote }}
  JWT_PRIVATE_KEY: {{ required "A valid .Values.secrets.JWT_PRIVATE_KEY is required!" .Values.secrets.JWT_PRIVATE_KEY | quote }}
  JWT_PUBLIC_KEY: {{ required "A valid .Values.secrets.JWT_PUBLIC_KEY is required!" .Values.secrets.JWT_PUBLIC_KEY | quote }}
  OIDC_REDIRECT_URI: {{ required "A valid .Values.secrets.OIDC_REDIRECT_URI is required!" .Values.secrets.OIDC_REDIRECT_URI | quote }}
  REDIS_URL: {{ required "A valid .Values.secrets.REDIS_URL is required!" .Values.secrets.REDIS_URL | quote }}
