apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-config
  labels:
    {{- include "web.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  VITE_API_URL: {{ .Values.env.VITE_API_URL | quote }}
  VITE_WS_URL: {{ .Values.env.VITE_WS_URL | quote }}
