apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}-secret
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_PUBLIC_KEY: {{ required "A valid .Values.secrets.JWT_PUBLIC_KEY is required!" .Values.secrets.JWT_PUBLIC_KEY | quote }}
