apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-document-service-secret
  labels:
    app: document-service
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{- range .Values.secretEnv }}
  {{ . }}: {{ required (printf "A valid .Values.secrets.%s is required!" .) (index $.Values.secrets .) | quote }}
  {{- end }}
